"""
Django settings for dataProcessingServer project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# ---------------------------------------------------------------------------
# Security settings — driven by environment variables.
#
# Required in production:
#   DJANGO_SECRET_KEY  — a long, random secret key
#
# Optional (have sensible dev defaults):
#   DJANGO_DEBUG           — set to "False" / "0" to disable debug mode
#   DJANGO_ALLOWED_HOSTS   — comma-separated list of allowed hostnames
# ---------------------------------------------------------------------------

# Detect whether we are running in development mode: if no explicit secret
# key is provided via the environment, we fall back to an insecure default
# and treat the environment as development.
_SECRET_KEY_ENV = os.getenv('DJANGO_SECRET_KEY')
_IS_DEV = _SECRET_KEY_ENV is None

if _IS_DEV:
    # Development-only fallback — NEVER use this in production.
    SECRET_KEY = 'django-insecure-dev-only-key-do-not-use-in-production'
else:
    SECRET_KEY = _SECRET_KEY_ENV

# SECURITY WARNING: don't run with debug turned on in production!
_debug_env = os.getenv('DJANGO_DEBUG')
if _debug_env is not None:
    DEBUG = _debug_env.lower() in ('true', '1', 'yes')
else:
    # Default to True only in development.
    DEBUG = _IS_DEV

# ALLOWED_HOSTS — populated from a comma-separated env var.
# On Render, when not explicitly set, fall back to the provided external hostname.
_allowed_hosts_env = os.getenv('DJANGO_ALLOWED_HOSTS', '')
_render_external_hostname = os.getenv('RENDER_EXTERNAL_HOSTNAME', '').strip()

if _allowed_hosts_env:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.split(',') if h.strip()]
elif _render_external_hostname:
    ALLOWED_HOSTS = [_render_external_hostname, 'localhost', '127.0.0.1']
else:
    ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'dataProcessingServer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'dataProcessingServer.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
